[package]
name = "miniftp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { version = "0.4", features = ["std", "serde"] }
mio = "0.8.0"
bytes = "1.1.0"
yaml-rust = "0.4.5"
nix = "0.23.0"
