server_addr: 0.0.0.0
server_port: 8089
pasv_enable: false
pasv_port:
  - 2222
  - 4444
max_clients: 1024
max_speed: 10240 # 10Mbyte/s
ssl_enable: false
rsa_cert_file: ~
rsa_private_key_file: ~
admin: "liwang"
users:
  liwang: "123456"
  anonymous: "123456"
